INHERIT: !ENV [NAV_YAML, nav.yml]
watch:
   - ./docs
   - ./overrides
   - mkdocs.yml
   - !ENV [NAV_YAML, nav.yml]
site_name: AMI Documentation
theme:
  name: material
  language: en
  logo: resources/logo.svg
  favicon: resources/favicon.ico
  font:
    text: Barlow
    code: Monaco, Menlo, Ubuntu Mono, Consolas, Source Code Pro, monospace
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  custom_dir: overrides
  icon:
    admonition:
      quote: fontawesome/solid/code
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/3forge/
      name: 3forge on LinkedIn
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@3forge461/videos/
      name: 3forge on YouTube
    - icon: material/web 
      link: https://3forge.com/
      name: 3forge.com
  analytics:
    provider: google
    property: G-YB1W2F9X99
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - tables
  - admonition
  - def_list
  - toc:
     permalink: true
     toc_depth: 3
     separator: "-"
plugins:
  - glightbox
  - search:
      lang: en