// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic.proto

package com.f1.test.protos;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ticker = 1;</code>
   */
  boolean hasTicker();
  /**
   * <code>optional string ticker = 1;</code>
   */
  java.lang.String getTicker();
  /**
   * <code>optional string ticker = 1;</code>
   */
  com.google.protobuf.ByteString
      getTickerBytes();

  /**
   * <code>optional int32 sharecount = 2;</code>
   */
  boolean hasSharecount();
  /**
   * <code>optional int32 sharecount = 2;</code>
   */
  int getSharecount();

  /**
   * <code>optional int32 price = 3;</code>
   */
  boolean hasPrice();
  /**
   * <code>optional int32 price = 3;</code>
   */
  int getPrice();
}
