// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.f1.test.protos;

public final class Stock {
  private Stock() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Stonk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Stonk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stock.proto\022\004test\":\n\005Stonk\022\016\n\006ticker\030\001" +
      " \001(\t\022\022\n\nsharecount\030\002 \001(\005\022\r\n\005price\030\003 \001(\002B" +
      "\026\n\022com.f1.test.protosP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_Stonk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Stonk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Stonk_descriptor,
        new java.lang.String[] { "Ticker", "Sharecount", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
