// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.f1.test.protos;

/**
 * Protobuf type {@code test.Stonk}
 */
public  final class Stonk extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.Stonk)
    StonkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Stonk.newBuilder() to construct.
  private Stonk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stonk() {
    ticker_ = "";
    sharecount_ = 0;
    price_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Stonk(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            ticker_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            sharecount_ = input.readInt32();
            break;
          }
          case 29: {
            bitField0_ |= 0x00000004;
            price_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.f1.test.protos.Stock.internal_static_test_Stonk_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.f1.test.protos.Stock.internal_static_test_Stonk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.f1.test.protos.Stonk.class, com.f1.test.protos.Stonk.Builder.class);
  }

  private int bitField0_;
  public static final int TICKER_FIELD_NUMBER = 1;
  private volatile java.lang.Object ticker_;
  /**
   * <code>optional string ticker = 1;</code>
   */
  public boolean hasTicker() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string ticker = 1;</code>
   */
  public java.lang.String getTicker() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        ticker_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string ticker = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTickerBytes() {
    java.lang.Object ref = ticker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHARECOUNT_FIELD_NUMBER = 2;
  private int sharecount_;
  /**
   * <code>optional int32 sharecount = 2;</code>
   */
  public boolean hasSharecount() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 sharecount = 2;</code>
   */
  public int getSharecount() {
    return sharecount_;
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private float price_;
  /**
   * <code>optional float price = 3;</code>
   */
  public boolean hasPrice() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional float price = 3;</code>
   */
  public float getPrice() {
    return price_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ticker_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, sharecount_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeFloat(3, price_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ticker_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, sharecount_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, price_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.f1.test.protos.Stonk)) {
      return super.equals(obj);
    }
    com.f1.test.protos.Stonk other = (com.f1.test.protos.Stonk) obj;

    boolean result = true;
    result = result && (hasTicker() == other.hasTicker());
    if (hasTicker()) {
      result = result && getTicker()
          .equals(other.getTicker());
    }
    result = result && (hasSharecount() == other.hasSharecount());
    if (hasSharecount()) {
      result = result && (getSharecount()
          == other.getSharecount());
    }
    result = result && (hasPrice() == other.hasPrice());
    if (hasPrice()) {
      result = result && (
          java.lang.Float.floatToIntBits(getPrice())
          == java.lang.Float.floatToIntBits(
              other.getPrice()));
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTicker()) {
      hash = (37 * hash) + TICKER_FIELD_NUMBER;
      hash = (53 * hash) + getTicker().hashCode();
    }
    if (hasSharecount()) {
      hash = (37 * hash) + SHARECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getSharecount();
    }
    if (hasPrice()) {
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.f1.test.protos.Stonk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.f1.test.protos.Stonk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.f1.test.protos.Stonk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.f1.test.protos.Stonk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.f1.test.protos.Stonk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.f1.test.protos.Stonk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.f1.test.protos.Stonk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Stonk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Stonk)
      com.f1.test.protos.StonkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.f1.test.protos.Stock.internal_static_test_Stonk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.f1.test.protos.Stock.internal_static_test_Stonk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.f1.test.protos.Stonk.class, com.f1.test.protos.Stonk.Builder.class);
    }

    // Construct using com.f1.test.protos.Stonk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ticker_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sharecount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      price_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.f1.test.protos.Stock.internal_static_test_Stonk_descriptor;
    }

    @java.lang.Override
    public com.f1.test.protos.Stonk getDefaultInstanceForType() {
      return com.f1.test.protos.Stonk.getDefaultInstance();
    }

    @java.lang.Override
    public com.f1.test.protos.Stonk build() {
      com.f1.test.protos.Stonk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.f1.test.protos.Stonk buildPartial() {
      com.f1.test.protos.Stonk result = new com.f1.test.protos.Stonk(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.ticker_ = ticker_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sharecount_ = sharecount_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.price_ = price_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.f1.test.protos.Stonk) {
        return mergeFrom((com.f1.test.protos.Stonk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.f1.test.protos.Stonk other) {
      if (other == com.f1.test.protos.Stonk.getDefaultInstance()) return this;
      if (other.hasTicker()) {
        bitField0_ |= 0x00000001;
        ticker_ = other.ticker_;
        onChanged();
      }
      if (other.hasSharecount()) {
        setSharecount(other.getSharecount());
      }
      if (other.hasPrice()) {
        setPrice(other.getPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.f1.test.protos.Stonk parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.f1.test.protos.Stonk) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object ticker_ = "";
    /**
     * <code>optional string ticker = 1;</code>
     */
    public boolean hasTicker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string ticker = 1;</code>
     */
    public java.lang.String getTicker() {
      java.lang.Object ref = ticker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ticker_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ticker = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ticker = 1;</code>
     */
    public Builder setTicker(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      ticker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ticker = 1;</code>
     */
    public Builder clearTicker() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ticker_ = getDefaultInstance().getTicker();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ticker = 1;</code>
     */
    public Builder setTickerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      ticker_ = value;
      onChanged();
      return this;
    }

    private int sharecount_ ;
    /**
     * <code>optional int32 sharecount = 2;</code>
     */
    public boolean hasSharecount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 sharecount = 2;</code>
     */
    public int getSharecount() {
      return sharecount_;
    }
    /**
     * <code>optional int32 sharecount = 2;</code>
     */
    public Builder setSharecount(int value) {
      bitField0_ |= 0x00000002;
      sharecount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 sharecount = 2;</code>
     */
    public Builder clearSharecount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sharecount_ = 0;
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <code>optional float price = 3;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public float getPrice() {
      return price_;
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public Builder setPrice(float value) {
      bitField0_ |= 0x00000004;
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float price = 3;</code>
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      price_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.Stonk)
  }

  // @@protoc_insertion_point(class_scope:test.Stonk)
  private static final com.f1.test.protos.Stonk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.f1.test.protos.Stonk();
  }

  public static com.f1.test.protos.Stonk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Stonk>
      PARSER = new com.google.protobuf.AbstractParser<Stonk>() {
    @java.lang.Override
    public Stonk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Stonk(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Stonk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stonk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.f1.test.protos.Stonk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

