[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = 'pymdown-lexers'
version = '1.3.0'
description = 'Pygments lexer package for PyMdown.'
dependencies = [
    'Pygments>=2.0.1'
]

[project.scripts]
criticmarkup = "pymdown_lexers:CriticMarkupLexer"
hex = "pymdown_lexers:HexLexer"
csscolor = "pymdown_lexers:CSSColorLexer"
amiscript = "pymdown_lexers:AmiScriptLexer"

