package com.f1.pofo.refdata;

import java.util.Map;

import com.f1.base.Message;
import com.f1.base.VID;

/**
 * represents an exchange
 * 
 */
@VID("F1.RD.EX")
public interface Exchange extends Message {

	/**
	 * @return the identifier (generated by the security master) which uniquely
	 *         identifies this exchanges
	 */
	public Integer getExchangeId();

	public void setExchangeId(Integer exchangeId);

	/**
	 * @return the country code of the country this exchange is in
	 */
	public String getCountryCode();

	public void setCountryCode(String countryCode);

	/**
	 * @return the region code of the region this exchange is in
	 */
	public String getRegionCode();

	public void setRegionCode(String regionCode);

	/**
	 * @return the segments for this exchange, key being the exchange segment id
	 */
	public Map<String, ExchangeSegment> getExchangeSegments();

	public void setExchangeSegments(Map<String, ExchangeSegment> exchangeId);
}
