package com.f1.pofo.refdata;

import java.util.Map;

import com.f1.base.Day;
import com.f1.base.Message;
import com.f1.base.VID;

@VID("F1.RD.SE")
public interface Security extends Message {

	byte IS_PRIMARY = 1;
	byte IS_COMPOSITE = 2;
	byte IS_INDEX = 4;

	/**
	 * @return the id which uniquely represents this security (generated by the
	 *         security master)
	 */
	public int getSecurityId();

	public void setSecurityId(int securityId);

	/**
	 * @return the type of instrument
	 */
	public String getInstrumentType();

	public void setInstrumentType(String instrumentType);

	/**
	 * @return the type of instrument
	 */
	public int getSecurityType();

	public void setSecurityType(int securityType);

	/**
	 * @return the exchange symbol
	 */
	public String getSymbol();

	public void setSymbol(String symbol);

	/**
	 * @return the reuters ric code
	 */
	public String getRic();

	public void setRic(String cusip);

	/**
	 * @return the cusip
	 */
	public String getCusip();

	public void setCusip(String cusip);

	/**
	 * @return the sedol
	 */
	public String getSedol();

	public void setSedol(String sedol);

	/**
	 * @return the isin code
	 */
	public String getIsin();

	public void setIsin(String isin);

	/**
	 * @return the size of an lot.
	 */
	public int getLotSize();

	public void setLotSize(int lotSize);

	public byte getAttributes();

	public void setAttributes(byte attributes);

	public Day getLastRefreshDate();

	public void setLastRefreshDate(Day lastRefreshDate);

	public int getStatus();

	public void setStatus(int status);

	public int getShortSellIndicator();

	public void setShortSellIndicator(int shortSellIndicator);

	/**
	 * @return custom symbololgies for a vendor. Key would be vendor name, and
	 *         value is there representation
	 */
	public Map<String, String> getVendorSymbologies();

	public void setVendorSymbologies(Map<String, String> symbologies);

	/**
	 * @return associated fundamentals. See
	 *         {@link Fundamentals#getFundamentalsId()}
	 */
	public int getFundamentalsId();

	public void setFundamentalsId(int fundamentalsId);

	public String getCurrency();

	public void setCurrency(String currency);

	public String getDescription();

	public void setDescription(String description);

	/**
	 * @return associated exchange. See {@link Exchange#getExchangeId()}
	 */
	public int getExchangeId();

	public void setExchangeId(int exchangeId);

	public String getExchangeSegmentCode();

	public void setExchangeSegmentCode(String exchangeSegmentCode);

}
