select 
  id,
  revision,
  created_on AS createdOn,
  mondified_on AS modifiedOn,
  enabled,
  username,
  status,
  first_name AS firstName,
  last_name AS lastName,
  company,
  phone,
  email,
  license_apps AS licenseApps,
  license_instances AS licenseInstances,
  trial_expires_on AS trialExpiresOn,
  license_expires_date AS licenseExpiresDate,
  license_days_length AS licenseDaysLength,
  password,
  role,
  intended_use as intendedUse,
  verify_guid as verifyGuid,
  forgot_guid as forgotGuid
FROM User WHERE active and ??{field}=?{value}