3Forge Trial Request Confirmation
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Trial Request Confirmation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body style="margin: 0; padding: 0;">

    <table bgcolor="#e2e2e2" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td>

          <table align="center" border="0" cellpadding="0" cellspacing="0" width="650" style="border-collapse: collapse;">

            <!-- logo -->
            <tr>
              <td align="center" bgcolor="#ffffff" style="padding: 40px 0 40px 0; font-size: 30px; color: #024960; font-weight: bold; font-family: Arial, sans-serif;">
                <img src="$resources$/images/new-logo-colored.png" alt="3Forge" width="200" style="display:block;"/>
              </td>
            </tr>

            <!-- hr -->
            <tr>
              <td bgcolor="#cccccc" style="padding: 1px 0">
            </tr>

            <!-- main -->
            <tr>
              <td bgcolor="#ffffff" style="padding: 40px 30px 40px 30px;">

                <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">

                  <tr>
                    <td align="center" style="font-size: 20px; font-family: Arial, sans-serif; line-height: 33px; color: #000000;">
                      <b>Your trial is in the works!</b>
                    </td>
                  </tr>

                  <tr>
                    <td style="padding: 30px 0 30px 0; margin: 0 20px 0; font-family: Arial, sans-serif; font-size: 18px; line-height: 25px; color: #000000;">
                      We will be in touch shortly to put together a proof of concept. In the meantime, get a head start on how to connect to databases, build dashboards and more.
                    </td>
                  </tr>

                  <!-- cta -->
                  <tr>
                    <td>

                      <table cellpadding="0" cellspacing="0" width="100%">

                        <tr>
                          <td width="209" valign="top">

                            <table cellpadding="0" cellspacing="0" width="100%">

                              <tr>
                                <a href="https://3forge.com/videos.htm" target="_blank"><img src="https://embed-ssl.wistia.com/deliveries/1d76516d0cadc43a8efeeb5de3bc6ace21f25bb8.jpg?image_crop_resized=418x236&image_play_button=true&image_play_button_size=2x&image_play_button_color=e27025e0" alt="Introduction" width="209" height="118" /></a>
                              </tr>

                              <tr>
                                <td style="padding: 20px 0 20px 0; margin: 0 20px 0; font-family: Arial, sans-serif; font-size: 16px; line-height: 22px; color: #000000;">
                                  Installation to insights in minutes. Our quick-start video tutorials guide you through the basics of AMI.
                                </td>
                              </tr>

                              <tr>
                                <td>

                                  <table border="0" cellpadding="0" cellspacing="0">

                                    <tr>
                                      <td bgcolor="#e27025" style="padding: 10px 15px 10px 15px; -webkit-border-radius:3px; border-radius:3px">
                                        <a href="https://3forge.com/videos.htm" target="_blank" style="font-size: 16px; font-family: Arial, sans-serif; color: #ffffff; text-decoration: none; display: inline-block;">Watch the videos</a>
                                      </td>
                                    </tr>

                                  </table>

                                </td>
                              </tr>

                            </table>

                          </td>

                          <td width="20" style="font-size: 0; line-height: 0;">
                            &nbsp;
                          </td>

                          <td width="209" valign="top">

                            <table cellpadding="0" cellspacing="0" width="100%">

                              <tr>
                                <a href="https://3forge.com/developer-tools?utm_source=3Forge&utm_medium=email&utm_campaign=trial-request-confirmation&utm_content=learn%20the%20tools" target="_blank">
                                  <img src="$resources$/images/drilldown.png" width="84%"/>
                                </a>
                              </tr>

                              <tr>
                                <td style="padding: 20px 0 20px 0; margin: 0 20px 0; font-family: Arial, sans-serif; font-size: 16px; line-height: 22px; color: #000000;">
                                  Want to know how it all works? See the features that make up the building blocks of every AMI dashboard.
                                </td>
                              </tr>

                              <tr>
                                <td>

                                  <table border="0" cellpadding="0" cellspacing="0">

                                    <tr>
                                      <td bgcolor="#e27025" style="padding: 10px 15px 10px 15px; -webkit-border-radius:3px; border-radius:3px">
                                        <a href="https://3forge.com/developer-tools?utm_source=3Forge&utm_medium=email&utm_campaign=trial-request-confirmation&utm_content=learn%20the%20tools" target="_blank" style="font-size: 16px; font-family: Arial, sans-serif; color: #ffffff; text-decoration: none; display: inline-block;">Learn the tools</a>
                                      </td>
                                    </tr>

                                  </table>

                                </td>
                              </tr>

                            </table>

                          </td>
                        </tr>

                      </table>

                    </td>
                  </tr>

                </table>

              </td>
            </tr>

            <!-- hr -->
            <tr>
              <td bgcolor="#cccccc" style="padding: 1px 0">
            </tr>

            <!-- footer -->
            <tr>
              <td bgcolor="#ffffff" style="padding: 30px 30px 30px 30px; color: #ffffff;">

                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                  <tr>
                    <td align="center" style="padding: 0 0 20px 0;">

                      <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                          <td>
                            <a href="https://www.linkedin.com/company/3forge" target="_blank">
                              <img src="$resources$/images/linkedin.png" alt="LinkedIn" width="20" style="display:block;"/>
                            </a>
                          </td>
                          <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
                          <td>
                            <a href="https://twitter.com/3forge_nyc" target="_blank">
                              <img src="$resources$/images/twitter.png" alt="Twitter" width="20" style="display:block;"/>
                            </a>
                          </td>
                          <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
                          <td>
                            <a href="https://www.facebook.com/3forge/" target="_blank">
                              <img src="$resources$/images/facebook.png" alt="Facebook" width="20" style="display:block;"/>
                            </a>
                          </td>
                        </tr>
                      </table>

                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="color: #000000; font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;"> Copyright 2018 3Forge, LLC</td>
                  </tr>
                  <tr>
                    <td align="center" style="color: #000000; font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;"> 225 Broadway, Suite 1615<br>New York, NY 10007</td>
                  </tr>
                  <tr>
                    <td align="center" style="font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;">
                      <a href="https://3forge.com/contact" target="_blank" style="color: #000000; text-decoration: none;">
                        +1 646 490 3733
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0">
                      <a href="https://3forge.com/contact" target="_blank" style="color: #000000; text-decoration: none;">
                        info@3forge.com
                      </a>
                    </td>
                  </tr>
                </table>

              </td>
            </tr>

          </table>

        </td>
      </tr>
    </table>

  </body>
</html>
