Press Release Request
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Press Release Request</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body style="margin: 0; padding: 0;">

    <table bgcolor="#e2e2e2" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td>

          <table align="center" border="0" cellpadding="0" cellspacing="0" width="650" style="border-collapse: collapse;">

            <!-- logo -->
            <tr>
              <td align="center" bgcolor="#ffffff" style="font-size: 30px; color: #024960; font-weight: bold; font-family: Arial, sans-serif;">
                <img src="$resources$/images/assets/logos/new_logo.png" alt="3Forge" width="200" style="display:block;"/>
              </td>
            </tr>

            <!-- img -->
            <tr>
              <td align="center">
                <img src="$resources$/images/assets/emailbanner.jpg" alt="banner" width="100%" style="display:block;"/>
              </td>
            </tr>

            <!-- main -->
            <tr>
              <td bgcolor="#ffffff" style="padding: 40px 30px 40px 30px;">

                <table border="0" cellpadding="0" cellspacing="0" width="100%" align="center">

				 <tr>
		          	<td>
		            	<h3>Press Release Download Request</h3>
		            </td>
		          </tr>
                  <tr>
                  
	                <td style="padding: 30px 0 30px 0; margin: 0 20px 0; font-family: Arial, sans-serif; font-size: 18px; line-height: 25px; color: #000000;">
		            	<h3><b>Account Details:</b></h3>
    					<ul>
                    		<li><b>Name</b>: $fname$ $lname$</li>
                    		<li><b>Company</b>: $company$</li>
                    		<li><b>Email</b>: $email$</li>
                    		<li><b>Phone</b>: $phone$</li>
                    		<li><b>Document Name</b>: $documentName$</li>
                    		<li><b>Contact by Phone</b>: $contact_phone$</li>
                    		<li><b>Contact by Email</b>: $contact_email$</li>
                    	</ul>
                    </td>
                  </tr>

                </table>

              </td>
            </tr>

            <!-- hr -->
            <tr>
              <td bgcolor="#cccccc" style="padding: 1px 0">
            </tr>

            <!-- footer -->
            <tr>
              <td bgcolor="#ffffff" style="padding: 30px 30px 30px 30px; color: #ffffff;">

                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                  <tr>
                    <td align="center" style="padding: 0 0 20px 0;">

                      <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                          <td>
                            <a href="https://www.linkedin.com/company/3forge" target="_blank">
                              <img src="$resources$/images/linkedin.png" alt="LinkedIn" width="20" style="display:block;"/>
                            </a>
                          </td>
                          <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
                          <td>
                            <a href="https://twitter.com/3forge_nyc" target="_blank">
                              <img src="$resources$/images/twitter.png" alt="Twitter" width="20" style="display:block;"/>
                            </a>
                          </td>
                          <td style="font-size: 0; line-height: 0;" width="20">&nbsp;</td>
                          <td>
                            <a href="https://www.facebook.com/3forge/" target="_blank">
                              <img src="$resources$/images/facebook.png" alt="Facebook" width="20" style="display:block;"/>
                            </a>
                          </td>
                        </tr>
                      </table>

                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="color: #000000; font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;"> Copyright 2018 3Forge, LLC</td>
                  </tr>
                  <tr>
                    <td align="center" style="color: #000000; font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;"> 225 Broadway, Suite 1615<br>New York, NY 10007</td>
                  </tr>
                  <tr>
                    <td align="center" style="font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0;">
                      <a href="https://3forge.com/contact" target="_blank" style="color: #000000; text-decoration: none;">
                        +1 646 490 3733
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="font-family: Arial, sans-serif; font-size: 14px; padding: 0 0 5px 0">
                      <a href="https://3forge.com/contact" target="_blank" style="color: #000000; text-decoration: none;">
                        info@3forge.com
                      </a>
                    </td>
                  </tr>
                </table>

              </td>
            </tr>

          </table>

        </td>
      </tr>
    </table>

  </body>
</html>
