package com.f1.ami.amicommon;

public interface AmiJdbcConsts {

	byte INSTRUCTION_LOGIN = 1;//returns a String
	byte INSTRUCTION_QUERY = 2;//returns a List [RET_CODE,value,RET_CODE,...]
	byte INSTRUCTION_INSERT = 3;//value is a List[TableName,ColNames,Table,Timeout]
	byte RET_CODE_ERROR = 1;//Value is String
	byte RET_CODE_TABLES = 2;//Value is a List<Table>
	byte RET_CODE_ROWS_EFFECTED = 3;//Value is Integer
	byte RET_CODE_RETURN_VALUE = 4;//Value is Object
	byte RET_CODE_GENERATED_KEYS = 5;//auto increment ids generated by inserts
	int VERSION_1 = 1;
	int VERSION_2 = 2;
}
