package com.f1.utils.ftp.client;

public interface FtpConstants {

	int FTP_PORT = 21;

	int CODE_NONE = -1;

	int CODE_100_REQUESTED_ACTION_INITIATED = 100;
	int CODE_110_RESTART_MARKER_REPLAY = 110;
	int CODE_120_SERVICE_READY_IN_NNN_MINUTES = 120;
	int CODE_125_DATA_CONNECTION_ALREADY_OPEN_XFER_STARTING = 125;
	int CODE_150_FILE_STATUS_OK_ABOUT_TO_OPEN_CONNECTION = 150;
	int CODE_200_COMMAND_OKAY = 200;
	int CODE_202_COMMAND_NOT_IMPLEMENTED_AT_THIS_SITE = 202;
	int CODE_211_SYSTEM_STATUS_OR_HELP_REPLY = 211;
	int CODE_212_DIRECTORY_STATUS = 212;
	int CODE_213_FILE_STATUS = 213;
	int CODE_214_HELP_MESSAGE = 214;
	int CODE_215_NAME_SYSTEM_TYPE = 215;
	int CODE_220_SERVICE_READ_FOR_NEW_USER = 220;
	int CODE_221_SERVICE_CLOSING_CONTROL_CONNECTION = 221;
	int CODE_225_DATA_CONNECTION_OPEN_NO_XFER_IN_PROGRESS = 225;
	int CODE_226_CLOSING_DATA_CONNECTION = 226;
	int CODE_227_ENTERING_PASSIVE_MODE = 227;
	int CODE_228_ENTERING_LONG_PASSIVE_MODE = 228;
	int CODE_229_ENTERING_EXTENDED_PASSIVE_MODE = 229;
	int CODE_230_USER_LOGGED_IN_PROCEED = 230;
	int CODE_231_USER_LOGGED_OUT_SERVICE_TERMINATED = 231;
	int CODE_232_LOGOUT_COMMAND_NOTED_WILL_COMPLETE_WHEN_XFER_DONE = 232;
	int CODE_250_REQUESTED_FILE_ACTION_OKAY_COMPLETED = 250;
	int CODE_257_PATHNAME_CREATED = 257;
	int CODE_331_USERNAME_OK_NEED_PASSWORD = 331;
	int CODE_332_NEED_ACCOUNT_FOR_LOGIN = 332;
	int CODE_350_REQUESTED_FILE_ACTION_PENDING_FURTHER_INFO = 350;
	int CODE_421_SERVICE_NOT_AVAILABLE = 421;
	int CODE_425_CANT_OPEN_DATA_CONNECTION = 425;
	int CODE_426_CONNECTION_CLOSED_XFER_ABORTED = 426;
	int CODE_434_REQUESTED_HOST_UNAVAILABLE = 434;
	int CODE_450_REQUESTED_FILE_ACTION_NOT_TAKEN = 450;
	int CODE_451_REQUESTED_ACTION_ABORTED = 451;
	int CODE_452_REQUESTED_ACTION_NOT_TAKEN_INSUFFICIENT_STORAGE = 452;
	int CODE_500_SYNTAX_ERROR_COMMAND_UNRECOGNIZED = 500;
	int CODE_501_SYNTAX_ERROR_IN_PARAMETERS = 501;
	int CODE_502_COMMAND_NOT_IMPLEMENTED = 502;
	int CODE_503_BAD_SEQUENCE_OF_COMMANDS = 503;
	int CODE_504_COMMAND_NOT_IMPLEMENTED_FOR_PARAMETER = 504;
	int CODE_530_NOT_LOGGED_IN = 530;
	int CODE_532_NEED_ACCOUNT_FOR_STORING_FILES = 532;
	int CODE_550_REQUESTED_ACTION_NOT_TAKEN_FILE_NOT_FOUND = 550;
	int CODE_551_REQUESTED_ACTION_ABORTED_PAGE_TYPE_UNKNOWN = 551;
	int CODE_552_ACTION_ABORTED_EXCEEDED_STORAGE_ALLOCATION = 552;
	int CODE_553_ACTION_NOT_TAKEN_FILENAME_NOT_ALLOWED = 553;

	String COMMAND_USER = "USER";
	String COMMAND_PASS = "PASS";
	String COMMAND_LIST = "LIST";
	String COMMAND_MLST = "MLST";
	String COMMAND_MLSD = "MLSD";
	String COMMAND_NLST = "NLST";
	String COMMAND_PASV = "PASV";
	String COMMAND_CWD = "CWD";
	String COMMAND_DELE = "DELE";
	String COMMAND_HELP = "HELP";
	String COMMAND_MDTM = "MDTM";
	String COMMAND_MKD = "MKD";
	String COMMAND_MODE = "MODE";
	String COMMAND_NOOP = "NOOP";
	String COMMAND_PWD = "PWD";
	String COMMAND_QUIT = "QUIT";
	String COMMAND_RETR = "RETR";
	String COMMAND_RMD = "RMD";
	String COMMAND_RNFR = "RNFR";
	String COMMAND_RNTO = "RNTO";
	String COMMAND_SITE = "SITE";
	String COMMAND_SIZE = "SIZE";
	String COMMAND_STOR = "STOR";
	String COMMAND_TYPE = "TYPE";
	String COMMAND_ACCT = "ACCT";
	String COMMAND_APPE = "APPE";
	String COMMAND_CDUP = "CDUP";
	String COMMAND_REIN = "REIN";
	String COMMAND_STAT = "STAT";
	String COMMAND_STOU = "STOU";
	String COMMAND_STRU = "STRU";
	String COMMAND_SYST = "SYST";

	char MODE_STREAM = 'S';
	char MODE_BLOCK = 'B';
	char MODE_COMPRESSED = 'C';

	char TYPE_ASCII_TEXT = 'A';
	char TYPE_EBCDIC_TEXT = 'E';
	char TYPE_IMAGE_BINARY_DATA = 'I';
	char TYPE_LOCAL_FORMAT = 'L';

}
