SELECT 
    a.id,
    a.revision,
    a.description,
    a.deployment_id as 'deploymentId',
    a.options,
    a.target_id as 'targetId',
    a.task_type as 'type',
    a.command,
    a.timezone,
    a.hours,
    a.minutes,
    a.seconds,
    a.weekdays,
    a.month_in_years as 'monthInYears',
    a.week_in_months as 'weekInMonths',
    a.week_in_years as 'weekInYears',
    a.day_in_months as 'dayInMonths',
    a.day_of_week_in_months as 'dayOfWeekInMonths',
    a.day_of_years as 'dayOfYears',
    a.comments as 'comments',
    a.state as 'state',
    a.metadata as '(STRINGMAP)metadata',
    b.status,
    b.now,
    b.message,
    b.invoked_by as 'invokedBy',
    b.next_runtime as 'nextRuntime',
    b.last_runtime as 'lastRuntime',
    b.run_count as 'runCount'
FROM  ScheduledTasks a JOIN ScheduledTaskStatuses b ON a.id=b.scheduled_task_id 
WHERE a.active and b.active
