SELECT 
    a.id,
    a.revision,
    a.deployment_set_id as deploymentSetId,
    a.procedure_id as procedureId,
    b.build_result_id as currentBuildResultId,
    b.build_invoked_by as currentBuildInvokedBy,
    a.target_machine_uid as targetMachineUid,
    a.target_user as targetUser,
    a.target_directory as targetDirectory,
    a.generated_properties_file as generatedPropertiesFile,
    a.start_script_file as startScriptFile,
    a.stop_script_file as stopScriptFile,
    a.properties as properties,
    a.env_vars as 'envVars',
    a.generated_files as '(STRINGMAP)generatedFiles',
    a.scripts_directory as scriptsDirectory,
    a.metadata as '(STRINGMAP)metadata',
    a.description as description,
    a.install_script_file as installScriptFile,
    a.uninstall_script_file as uninstallScriptFile,
    a.verify_script_file as verifyScriptFile,
    a.auto_delete_files as 'autoDeleteFiles',
    a.log_directories as 'logDirectories',
    a.options,
    b.status,
    b.now,
    b.running_pid as 'runningPid',
    b.running_process_uid as 'runningProcessUid',
    b.deployed_instance_id as 'deployedInstanceId',
    b.message
FROM  Deployments a JOIN DeploymentStatuses b ON a.id=b.deployment_id 
WHERE a.active and b.active
