!function(b){b(function(){var e=b.support;a:{var f=document.createElement("bootstrap");var a={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in a)if(void 0!==f.style[c]){f=a[c];break a}f=void 0}e.transition=f&&{end:f}})}(window.jQuery);
!function(b){var e=function(a){b(a).on("click",'[data-dismiss="alert"]',this.close)};e.prototype.close=function(a){function c(){e.trigger("closed").remove()}var d=b(this),g=d.attr("data-target");g||(g=(g=d.attr("href"))&&g.replace(/.*(?=#[^\s]*$)/,""));var e=b(g);a&&a.preventDefault();e.length||(e=d.hasClass("alert")?d:d.parent());e.trigger(a=b.Event("close"));a.isDefaultPrevented()||(e.removeClass("in"),b.support.transition&&e.hasClass("fade")?e.on(b.support.transition.end,c):c())};var f=b.fn.alert;
b.fn.alert=function(a){return this.each(function(){var c=b(this),d=c.data("alert");d||c.data("alert",d=new e(this));"string"==typeof a&&d[a].call(c)})};b.fn.alert.Constructor=e;b.fn.alert.noConflict=function(){b.fn.alert=f;return this};b(document).on("click.alert.data-api",'[data-dismiss="alert"]',e.prototype.close)}(window.jQuery);
!function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.button.defaults,c)};e.prototype.setState=function(a){var b=this.$element,d=b.data(),g=b.is("input")?"val":"html";a+="Text";d.resetText||b.data("resetText",b[g]());b[g](d[a]||this.options[a]);setTimeout(function(){"loadingText"==a?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)};e.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};var f=b.fn.button;b.fn.button=function(a){return this.each(function(){var c=b(this),d=c.data("button"),g="object"==typeof a&&a;d||c.data("button",d=new e(this,g));"toggle"==a?d.toggle():a&&d.setState(a)})};b.fn.button.defaults={loadingText:"loading..."};b.fn.button.Constructor=e;b.fn.button.noConflict=function(){b.fn.button=f;return this};b(document).on("click.button.data-api","[data-toggle^=button]",function(a){a=b(a.target);
a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})}(window.jQuery);
!function(b){var e=function(a,c){this.$element=b(a);this.options=c;"hover"==this.options.pause&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};e.prototype={cycle:function(a){a||(this.paused=!1);this.options.interval&&!this.paused&&(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this},to:function(a){var c=this.$element.find(".item.active"),d=c.parent().children();c=d.index(c);var g=this;if(!(a>d.length-1||0>a))return this.sliding?
this.$element.one("slid",function(){g.to(a)}):c==a?this.pause().cycle():this.slide(a>c?"next":"prev",b(d[a]))},pause:function(a){a||(this.paused=!0);this.$element.find(".next, .prev").length&&b.support.transition.end&&(this.$element.trigger(b.support.transition.end),this.cycle());clearInterval(this.interval);this.interval=null;return this},next:function(){if(!this.sliding)return this.slide("next")},prev:function(){if(!this.sliding)return this.slide("prev")},slide:function(a,c){var d=this.$element.find(".item.active"),
g=c||d[a](),e=this.interval,f="next"==a?"left":"right",h="next"==a?"first":"last",m=this;this.sliding=!0;e&&this.pause();g=g.length?g:this.$element.find(".item")[h]();h=b.Event("slide",{relatedTarget:g[0]});if(!g.hasClass("active")){if(b.support.transition&&this.$element.hasClass("slide")){this.$element.trigger(h);if(h.isDefaultPrevented())return;g.addClass(a);g[0].offsetWidth;d.addClass(f);g.addClass(f);this.$element.one(b.support.transition.end,function(){g.removeClass([a,f].join(" ")).addClass("active");
d.removeClass(["active",f].join(" "));m.sliding=!1;setTimeout(function(){m.$element.trigger("slid")},0)})}else{this.$element.trigger(h);if(h.isDefaultPrevented())return;d.removeClass("active");g.addClass("active");this.sliding=!1;this.$element.trigger("slid")}e&&this.cycle();return this}}};var f=b.fn.carousel;b.fn.carousel=function(a){return this.each(function(){var c=b(this),d=c.data("carousel"),g=b.extend({},b.fn.carousel.defaults,"object"==typeof a&&a),l="string"==typeof a?a:g.slide;d||c.data("carousel",
d=new e(this,g));if("number"==typeof a)d.to(a);else if(l)d[l]();else g.interval&&d.cycle()})};b.fn.carousel.defaults={interval:5E3,pause:"hover"};b.fn.carousel.Constructor=e;b.fn.carousel.noConflict=function(){b.fn.carousel=f;return this};b(document).on("click.carousel.data-api","[data-slide]",function(a){var c=b(this),d,g=b(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""));c=b.extend({},g.data(),c.data());g.carousel(c);a.preventDefault()})}(window.jQuery);
!function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.collapse.defaults,c);this.options.parent&&(this.$parent=b(this.options.parent));this.options.toggle&&this.toggle()};e.prototype={constructor:e,dimension:function(){return this.$element.hasClass("width")?"width":"height"},show:function(){var a,c;if(!this.transitioning){var d=this.dimension();var g=b.camelCase(["scroll",d].join("-"));if((a=this.$parent&&this.$parent.find("> .accordion-group > .in"))&&a.length){if((c=a.data("collapse"))&&
c.transitioning)return;a.collapse("hide");c||a.data("collapse",null)}this.$element[d](0);this.transition("addClass",b.Event("show"),"shown");b.support.transition&&this.$element[d](this.$element[0][g])}},hide:function(){if(!this.transitioning){var a=this.dimension();this.reset(this.$element[a]());this.transition("removeClass",b.Event("hide"),"hidden");this.$element[a](0)}},reset:function(a){var b=this.dimension();this.$element.removeClass("collapse")[b](a||"auto")[0].offsetWidth;this.$element[null!==
a?"addClass":"removeClass"]("collapse");return this},transition:function(a,c,d){var g=this,e=function(){"show"==c.type&&g.reset();g.transitioning=0;g.$element.trigger(d)};this.$element.trigger(c);c.isDefaultPrevented()||(this.transitioning=1,this.$element[a]("in"),b.support.transition&&this.$element.hasClass("collapse")?this.$element.one(b.support.transition.end,e):e())},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};var f=b.fn.collapse;b.fn.collapse=function(a){return this.each(function(){var c=
b(this),d=c.data("collapse"),g="object"==typeof a&&a;d||c.data("collapse",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.collapse.defaults={toggle:!0};b.fn.collapse.Constructor=e;b.fn.collapse.noConflict=function(){b.fn.collapse=f;return this};b(document).on("click.collapse.data-api","[data-toggle=collapse]",function(a){var c=b(this),d;a=c.attr("data-target")||a.preventDefault()||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"");d=b(a).data("collapse")?"toggle":c.data();c[b(a).hasClass("in")?
"addClass":"removeClass"]("collapsed");b(a).collapse(d)})}(window.jQuery);
!function(b){function e(){b("[data-toggle=dropdown]").each(function(){f(b(this)).removeClass("open")})}function f(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));c=b(c);c.length||(c=a.parent());return c}var a=function(a){var c=b(a).on("click.dropdown.data-api",this.toggle);b("html").on("click.dropdown.data-api",function(){c.parent().removeClass("open")})};a.prototype={constructor:a,toggle:function(a){a=b(this);if(!a.is(".disabled, :disabled")){var c=
f(a);var d=c.hasClass("open");e();d||c.toggleClass("open");a.focus();return!1}},keydown:function(a){if(/(38|40|27)/.test(a.keyCode)){var c=b(this);a.preventDefault();a.stopPropagation();if(!c.is(".disabled, :disabled")){var d=f(c);var e=d.hasClass("open");if(!e||e&&27==a.keyCode)return c.click();c=b("[role=menu] li:not(.divider):visible a",d);c.length&&(d=c.index(c.filter(":focus")),38==a.keyCode&&0<d&&d--,40==a.keyCode&&d<c.length-1&&d++,~d||(d=0),c.eq(d).focus())}}}};var c=b.fn.dropdown;b.fn.dropdown=
function(c){return this.each(function(){var d=b(this),e=d.data("dropdown");e||d.data("dropdown",e=new a(this));"string"==typeof c&&e[c].call(d)})};b.fn.dropdown.Constructor=a;b.fn.dropdown.noConflict=function(){b.fn.dropdown=c;return this};b(document).on("click.dropdown.data-api touchstart.dropdown.data-api",e).on("click.dropdown touchstart.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("touchstart.dropdown.data-api",".dropdown-menu",function(a){a.stopPropagation()}).on("click.dropdown.data-api touchstart.dropdown.data-api",
"[data-toggle=dropdown]",a.prototype.toggle).on("keydown.dropdown.data-api touchstart.dropdown.data-api","[data-toggle=dropdown], [role=menu]",a.prototype.keydown)}(window.jQuery);
!function(b){var e=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",b.proxy(this.hide,this));this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};e.prototype={constructor:e,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var a=this,c=b.Event("show");this.$element.trigger(c);this.isShown||c.isDefaultPrevented()||(this.isShown=!0,this.escape(),this.backdrop(function(){var c=b.support.transition&&
a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();c&&a.$element[0].offsetWidth;a.$element.addClass("in").attr("aria-hidden",!1);a.enforceFocus();c?a.$element.one(b.support.transition.end,function(){a.$element.focus().trigger("shown")}):a.$element.focus().trigger("shown")}))},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),b(document).off("focusin.modal"),
this.$element.removeClass("in").attr("aria-hidden",!0),b.support.transition&&this.$element.hasClass("fade")?this.hideWithTransition():this.hideModal())},enforceFocus:function(){var a=this;b(document).on("focusin.modal",function(b){a.$element[0]===b.target||a.$element.has(b.target).length||a.$element.focus()})},escape:function(){var a=this;if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.modal",function(b){27==b.which&&a.hide()});else this.isShown||this.$element.off("keyup.dismiss.modal")},
hideWithTransition:function(){var a=this,c=setTimeout(function(){a.$element.off(b.support.transition.end);a.hideModal()},500);this.$element.one(b.support.transition.end,function(){clearTimeout(c);a.hideModal()})},hideModal:function(a){this.$element.hide().trigger("hidden");this.backdrop()},removeBackdrop:function(){this.$backdrop.remove();this.$backdrop=null},backdrop:function(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=b.support.transition&&c;this.$backdrop=
b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$backdrop.click("static"==this.options.backdrop?b.proxy(this.$element[0].focus,this.$element[0]):b.proxy(this.hide,this));d&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");d?this.$backdrop.one(b.support.transition.end,a):a()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,b.proxy(this.removeBackdrop,
this)):this.removeBackdrop()):a&&a()}};var f=b.fn.modal;b.fn.modal=function(a){return this.each(function(){var c=b(this),d=c.data("modal"),g=b.extend({},b.fn.modal.defaults,c.data(),"object"==typeof a&&a);d||c.data("modal",d=new e(this,g));if("string"==typeof a)d[a]();else g.show&&d.show()})};b.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};b.fn.modal.Constructor=e;b.fn.modal.noConflict=function(){b.fn.modal=f;return this};b(document).on("click.modal.data-api",'[data-toggle="modal"]',function(a){var c=
b(this),d=c.attr("href"),g=b(c.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""));d=g.data("modal")?"toggle":b.extend({remote:!/#/.test(d)&&d},g.data(),c.data());a.preventDefault();g.modal(d).one("hide",function(){c.focus()})})}(window.jQuery);
!function(b){var e=function(a,b){this.init("tooltip",a,b)};e.prototype={constructor:e,init:function(a,c,d){this.type=a;this.$element=b(c);this.options=this.getOptions(d);this.enabled=!0;if("click"==this.options.trigger)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else"manual"!=this.options.trigger&&(a="hover"==this.options.trigger?"mouseenter":"focus",c="hover"==this.options.trigger?"mouseleave":"blur",this.$element.on(a+"."+this.type,this.options.selector,
b.proxy(this.enter,this)),this.$element.on(c+"."+this.type,this.options.selector,b.proxy(this.leave,this)));this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=b.extend({},b.fn[this.type].defaults,a,this.$element.data());a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a},enter:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);if(!c.options.delay||!c.options.delay.show)return c.show();
clearTimeout(this.timeout);c.hoverState="in";this.timeout=setTimeout(function(){"in"==c.hoverState&&c.show()},c.options.delay.show)},leave:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);this.timeout&&clearTimeout(this.timeout);if(!c.options.delay||!c.options.delay.hide)return c.hide();c.hoverState="out";this.timeout=setTimeout(function(){"out"==c.hoverState&&c.hide()},c.options.delay.hide)},show:function(){if(this.hasContent()&&this.enabled){var a=this.tip();this.setContent();
this.options.animation&&a.addClass("fade");var b="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;var d=/in/.test(b);a.detach().css({top:0,left:0,display:"block"}).insertAfter(this.$element);var g=this.getPosition(d);var e=a[0].offsetWidth;var f=a[0].offsetHeight;switch(d?b.split(" ")[1]:b){case "bottom":var h={top:g.top+g.height,left:g.left+g.width/2-e/2};break;case "top":h={top:g.top-f,left:g.left+g.width/2-e/2};break;case "left":h=
{top:g.top+g.height/2-f/2,left:g.left-e};break;case "right":h={top:g.top+g.height/2-f/2,left:g.left+g.width}}a.offset(h).addClass(b).addClass("in")}},setContent:function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](b);a.removeClass("fade in top bottom left right")},hide:function(){function a(){var a=setTimeout(function(){c.off(b.support.transition.end).detach()},500);c.one(b.support.transition.end,function(){clearTimeout(a);c.detach()})}var c=this.tip();
c.removeClass("in");b.support.transition&&this.$tip.hasClass("fade")?a():c.detach();return this},fixTitle:function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},getPosition:function(a){return b.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a=
this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)},tip:function(){return this.$tip=this.$tip||b(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(a){a=b(a.currentTarget)[this.type](this._options).data(this.type);a[a.tip().hasClass("in")?
"hide":"show"]()},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}};var f=b.fn.tooltip;b.fn.tooltip=function(a){return this.each(function(){var c=b(this),d=c.data("tooltip"),g="object"==typeof a&&a;d||c.data("tooltip",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.tooltip.Constructor=e;b.fn.tooltip.defaults={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover",
title:"",delay:0,html:!1};b.fn.tooltip.noConflict=function(){b.fn.tooltip=f;return this}}(window.jQuery);
!function(b){var e=function(a,b){this.init("popover",a,b)};e.prototype=b.extend({},b.fn.tooltip.Constructor.prototype,{constructor:e,setContent:function(){var a=this.tip(),b=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content")[this.options.html?"html":"text"](d);a.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a=this.$element,b=this.options;
return a.attr("data-content")||("function"==typeof b.content?b.content.call(a[0]):b.content)},tip:function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}});var f=b.fn.popover;b.fn.popover=function(a){return this.each(function(){var c=b(this),d=c.data("popover"),g="object"==typeof a&&a;d||c.data("popover",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.popover.Constructor=e;b.fn.popover.defaults=
b.extend({},b.fn.tooltip.defaults,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"></div></div></div>'});b.fn.popover.noConflict=function(){b.fn.popover=f;return this}}(window.jQuery);
!function(b){function e(a,c){var d=b.proxy(this.process,this),g=b(a).is("body")?b(window):b(a),e;this.options=b.extend({},b.fn.scrollspy.defaults,c);this.$scrollElement=g.on("scroll.scroll-spy.data-api",d);this.selector=(this.options.target||(e=b(a).attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.$body=b("body");this.refresh();this.process()}e.prototype={constructor:e,refresh:function(){var a=this;this.offsets=b([]);this.targets=b([]);this.$body.find(this.selector).map(function(){var c=
b(this);c=c.data("target")||c.attr("href");var d=/^#\w/.test(c)&&b(c);return d&&d.length&&[[d.position().top+a.$scrollElement.scrollTop(),c]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})},process:function(){var a=this.$scrollElement.scrollTop()+this.options.offset,b=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),d=this.offsets,g=this.targets,e=this.activeTarget,f;if(a>=b)return e!=(f=
g.last()[0])&&this.activate(f);for(f=d.length;f--;)e!=g[f]&&a>=d[f]&&(!d[f+1]||a<=d[f+1])&&this.activate(g[f])},activate:function(a){this.activeTarget=a;b(this.selector).parent(".active").removeClass("active");a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parent("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate")}};var f=b.fn.scrollspy;b.fn.scrollspy=function(a){return this.each(function(){var c=
b(this),d=c.data("scrollspy"),g="object"==typeof a&&a;d||c.data("scrollspy",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.scrollspy.Constructor=e;b.fn.scrollspy.defaults={offset:10};b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=f;return this};b(window).on("load",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);a.scrollspy(a.data())})})}(window.jQuery);
!function(b){var e=function(a){this.element=b(a)};e.prototype={constructor:e,show:function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.attr("data-target");d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var g=c.find(".active:last a")[0];var e=b.Event("show",{relatedTarget:g});a.trigger(e);e.isDefaultPrevented()||(d=b(d),this.activate(a.parent("li"),c),this.activate(d,d.parent(),function(){a.trigger({type:"shown",relatedTarget:g})}))}},
activate:function(a,c,d){function e(){f.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");k?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var f=c.find("> .active"),k=d&&b.support.transition&&f.hasClass("fade");k?f.one(b.support.transition.end,e):e();f.removeClass("in")}};var f=b.fn.tab;b.fn.tab=function(a){return this.each(function(){var c=b(this),d=c.data("tab");
d||c.data("tab",d=new e(this));if("string"==typeof a)d[a]()})};b.fn.tab.Constructor=e;b.fn.tab.noConflict=function(){b.fn.tab=f;return this};b(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})}(window.jQuery);
!function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.typeahead.defaults,c);this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.updater=this.options.updater||this.updater;this.source=this.options.source;this.$menu=b(this.options.menu);this.shown=!1;this.listen()};e.prototype={constructor:e,select:function(){var a=this.$menu.find(".active").attr("data-value");this.$element.val(this.updater(a)).change();
return this.hide()},updater:function(a){return a},show:function(){var a=b.extend({},this.$element.position(),{height:this.$element[0].offsetHeight});this.$menu.insertAfter(this.$element).css({top:a.top+a.height,left:a.left}).show();this.shown=!0;return this},hide:function(){this.$menu.hide();this.shown=!1;return this},lookup:function(a){this.query=this.$element.val();return!this.query||this.query.length<this.options.minLength?this.shown?this.hide():this:(a=b.isFunction(this.source)?this.source(this.query,
b.proxy(this.process,this)):this.source)?this.process(a):this},process:function(a){var c=this;a=b.grep(a,function(a){return c.matcher(a)});a=this.sorter(a);return a.length?this.render(a.slice(0,this.options.items)).show():this.shown?this.hide():this},matcher:function(a){return~a.toLowerCase().indexOf(this.query.toLowerCase())},sorter:function(a){for(var b=[],d=[],e=[],f;f=a.shift();)f.toLowerCase().indexOf(this.query.toLowerCase())?~f.indexOf(this.query)?d.push(f):e.push(f):b.push(f);return b.concat(d,
e)},highlighter:function(a){var b=this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&");return a.replace(new RegExp("("+b+")","ig"),function(a,b){return"<strong>"+b+"</strong>"})},render:function(a){var c=this;a=b(a).map(function(a,e){a=b(c.options.item).attr("data-value",e);a.find("a").html(c.highlighter(e));return a[0]});a.first().addClass("active");this.$menu.html(a);return this},next:function(a){a=this.$menu.find(".active").removeClass("active").next();a.length||(a=b(this.$menu.find("li")[0]));
a.addClass("active")},prev:function(a){a=this.$menu.find(".active").removeClass("active").prev();a.length||(a=this.$menu.find("li").last());a.addClass("active")},listen:function(){this.$element.on("blur",b.proxy(this.blur,this)).on("keypress",b.proxy(this.keypress,this)).on("keyup",b.proxy(this.keyup,this));if(this.eventSupported("keydown"))this.$element.on("keydown",b.proxy(this.keydown,this));this.$menu.on("click",b.proxy(this.click,this)).on("mouseenter","li",b.proxy(this.mouseenter,this))},eventSupported:function(a){var b=
a in this.$element;b||(this.$element.setAttribute(a,"return;"),b="function"===typeof this.$element[a]);return b},move:function(a){if(this.shown){switch(a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:a.preventDefault();this.prev();break;case 40:a.preventDefault(),this.next()}a.stopPropagation()}},keydown:function(a){this.suppressKeyPressRepeat=~b.inArray(a.keyCode,[40,38,9,13,27]);this.move(a)},keypress:function(a){this.suppressKeyPressRepeat||this.move(a)},keyup:function(a){switch(a.keyCode){case 40:case 38:case 16:case 17:case 18:break;
case 9:case 13:if(!this.shown)return;this.select();break;case 27:if(!this.shown)return;this.hide();break;default:this.lookup()}a.stopPropagation();a.preventDefault()},blur:function(a){var b=this;setTimeout(function(){b.hide()},150)},click:function(a){a.stopPropagation();a.preventDefault();this.select()},mouseenter:function(a){this.$menu.find(".active").removeClass("active");b(a.currentTarget).addClass("active")}};var f=b.fn.typeahead;b.fn.typeahead=function(a){return this.each(function(){var c=b(this),
d=c.data("typeahead"),g="object"==typeof a&&a;d||c.data("typeahead",d=new e(this,g));if("string"==typeof a)d[a]()})};b.fn.typeahead.defaults={source:[],items:8,menu:'<ul class="typeahead dropdown-menu"></ul>',item:'<li><a href="#"></a></li>',minLength:1};b.fn.typeahead.Constructor=e;b.fn.typeahead.noConflict=function(){b.fn.typeahead=f;return this};b(document).on("focus.typeahead.data-api",'[data-provide="typeahead"]',function(a){var c=b(this);c.data("typeahead")||(a.preventDefault(),c.typeahead(c.data()))})}(window.jQuery);
!function(b){var e=function(a,c){this.options=b.extend({},b.fn.affix.defaults,c);this.$window=b(window).on("scroll.affix.data-api",b.proxy(this.checkPosition,this)).on("click.affix.data-api",b.proxy(function(){setTimeout(b.proxy(this.checkPosition,this),1)},this));this.$element=b(a);this.checkPosition()};e.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=b(document).height(),c=this.$window.scrollTop(),d=this.$element.offset(),e=this.options.offset,f=e.bottom,k=e.top;"object"!=
typeof e&&(f=k=e);"function"==typeof k&&(k=e.top());"function"==typeof f&&(f=e.bottom());a=null!=this.unpin&&c+this.unpin<=d.top?!1:null!=f&&d.top+this.$element.height()>=a-f?"bottom":null!=k&&c<=k?"top":!1;this.affixed!==a&&(this.affixed=a,this.unpin="bottom"==a?d.top-c:null,this.$element.removeClass("affix affix-top affix-bottom").addClass("affix"+(a?"-"+a:"")))}};var f=b.fn.affix;b.fn.affix=function(a){return this.each(function(){var c=b(this),d=c.data("affix"),f="object"==typeof a&&a;d||c.data("affix",
d=new e(this,f));if("string"==typeof a)d[a]()})};b.fn.affix.Constructor=e;b.fn.affix.defaults={offset:0};b.fn.affix.noConflict=function(){b.fn.affix=f;return this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};c.offsetBottom&&(c.offset.bottom=c.offsetBottom);c.offsetTop&&(c.offset.top=c.offsetTop);a.affix(c)})})}(window.jQuery);
function tab(b){"menuInfoTab1"==b?(toggle("menuInfoTab1"),toggle("menuInfoTab2"),hide("menuInfoForm2"),show("menuInfoForm1")):"menuInfoTab2"==b?(toggle("menuInfoTab1"),toggle("menuInfoTab2"),hide("menuInfoForm1"),show("menuInfoForm2")):"menuInfoTab3"==b?(toggle("menuInfoTab1"),toggle("menuInfoTab2"),hide("menuInfoForm1"),hide("menuInfoForm2")):"menuInfoTabHide"==b?(hide("menuInfoTab1"),hide("menuInfoTab2"),hide("menuInfoFormDiv"),hide("menuInfoWrapper"),hide("menuInfoTabHide"),show("menuInfoTabShow")):
"menuInfoTabShow"==b&&(show("menuInfoTab1"),show("menuInfoTab2"),show("menuInfoFormDiv"),show("menuInfoWrapper"),hide("menuInfoTabShow"),show("menuInfoTabHide"))}function toggle(b){activated(b)?deactivate(b):activate(b)}function hide(b){docAddClass(b,"hidden")}function show(b){docRemoveClass(b,"hidden")}function activate(b){docRemoveClass(b,"inActive");docAddClass(b,"active")}function deactivate(b){docRemoveClass(b,"active");docAddClass(b,"inActive")}
function activated(b){return-1==docGet(b).className.search("active")?!1:!0}function docGet(b){return document.getElementById(b)}function docAddClass(b,e){var f=docGet(b);0>=f.className.length?f.className=e:-1==f.className.search(e)&&(f.className=f.className+" "+e)}function docRemoveClass(b,e){var f=docGet(b);0<f.className.length&&-1!=f.className.search(e)&&(f.className=f.className.replace(e,""))}
