package com.f1.pofo.oms;

import com.f1.base.Message;
import com.f1.base.PID;
import com.f1.pofo.fix.FixMsg;

/**
 * 
 * an oms client action (an action generated by the client, destined for the oms)
 * 
 */
public interface OmsClientAction extends Message {

	/**
	 * @return the id of the order this action is for
	 */
	@PID(84)
	public String getOrderID();
	public void setOrderID(String id);

	/**
	 * @return the id of the root order this action is for.
	 */
	@PID(85)
	public String getRootOrderID();
	public void setRootOrderID(String rootid);

	/**
	 * @return type of action
	 */
	@PID(86)
	public OmsAction getOrderAction();
	public void setOrderAction(OmsAction action);

	/**
	 * @return optional, custom user data
	 */
	@PID(87)
	public Object getUserData();
	public void setUserData(Object data);

	/**
	 * @return fix text (typically tag 58)
	 */
	@PID(88)
	public String getText();
	public void setText(String text);

	/**
	 * @return the actual fix message
	 */
	@PID(89)
	public FixMsg getEventDetails();
	public void setEventDetails(FixMsg event);

	/**
	 * @return the id of this request
	 */
	@PID(90)
	public ChildOrderRequest getChildRequest();
	public void setChildRequest(ChildOrderRequest request);

}
