package com.f1.pofo.oms;

import com.f1.base.VID;
import com.f1.base.ValuedEnum;

/**
 * 
 * Indicates the type of order. For completeness,orders can be sliced many times
 * at many levels. For example, in the following tree we see 2 levels of
 * internal slicing between the client and child slices:
 * 
 * <PRE>
 * CLIENT_ORDER
 *    +---> INTERNAL_SLICE
 *    |         +---> INTERNAL_SLICE
 *    |                   +---> SLICE
 *    |                   +---> SLICE
 *    +---> INTERNAL_SLICE
 *              +---> INTERNAL_SLICE
 *                        +---> SLICE
 *                        +---> SLICE
 * </PRE>
 * 
 * Quantities should "roll up" from slices to there parent.
 * 
 */
@VID("F1.OM.ST")
public enum SliceType implements ValuedEnum<Byte> {
	/**
	 * this is a client order(received from a client)
	 */
	CLIENT_ORDER(1),

	/**
	 * an internal slice which is unknown by both the client and street. Used to
	 * internally represent changes
	 */

	INTERNAL_SLICE(2),

	/**
	 * this is a slice order(generated by this oms and sent to the street)
	 */
	SLICE(3);

	final public byte type;

	private SliceType(int type) {
		this.type = (byte) type;
	}

	@Override
	public Byte getEnumValue() {
		return type;
	}
}
