package com.f1.anvil.triggers;

import com.f1.ami.center.table.AmiColumn;
import com.f1.ami.center.table.AmiImdb;
import com.f1.ami.center.table.AmiTable;

public class AnvilSchema {

	public final AmiTable childOrderTable;
	public final AmiColumn childOrderTable_chainId;
	public final AmiColumn childOrderTable_clOrderId;
	public final AmiColumn childOrderTable_limitPx;
	public final AmiColumn childOrderTable_baseCurrency;
	public final AmiColumn childOrderTable_baseLimitPx;
	public final AmiColumn childOrderTable_origClOrderId;
	public final AmiColumn childOrderTable_parentId;
	public final AmiColumn childOrderTable_qty;
	public final AmiColumn childOrderTable_status;
	public final AmiColumn childOrderTable_symbol;
	public final AmiColumn childOrderTable_time;

	public final AmiTable childModifyTable;
	public final AmiColumn childModifyTable_chainId;
	public final AmiColumn childModifyTable_clOrderId;
	public final AmiColumn childModifyTable_status;
	public final AmiColumn childModifyTable_symbol;
	public final AmiColumn childModifyTable_time;

	public final AmiTable childOrdersTable;
	public final AmiColumn childOrdersTable_availQty;
	public final AmiColumn childOrdersTable_availVal;
	public final AmiColumn childOrdersTable_chainId;
	public final AmiColumn childOrdersTable_clOrderId;
	public final AmiColumn childOrdersTable_filledQty;
	public final AmiColumn childOrdersTable_filledValue;
	public final AmiColumn childOrdersTable_limitPx;
	public final AmiColumn childOrdersTable_baseCurrency;
	public final AmiColumn childOrdersTable_baseLimitPx;
	public final AmiColumn childOrdersTable_openQty;
	public final AmiColumn childOrdersTable_time;
	public final AmiColumn childOrdersTable_updateTime;
	public final AmiColumn childOrdersTable_openVal;
	public final AmiColumn childOrdersTable_parentId;
	public final AmiColumn childOrdersTable_pendingCnt;
	public final AmiColumn childOrdersTable_pendingLatency;
	public final AmiColumn childOrdersTable_processedCnt;
	public final AmiColumn childOrdersTable_processedLatency;
	public final AmiColumn childOrdersTable_qty;
	public final AmiColumn childOrdersTable_replaced;
	public final AmiColumn childOrdersTable_status;
	public final AmiColumn childOrdersTable_symbol;

	public final AmiTable exTable;
	public final AmiColumn exTable_account;
	public final AmiColumn exTable_ex;
	public final AmiColumn exTable_execIndicator;
	public final AmiColumn exTable_industry;
	public final AmiColumn exTable_oID;
	public final AmiColumn exTable_execId;
	public final AmiColumn exTable_parentId;
	public final AmiColumn exTable_prevClose;
	public final AmiColumn exTable_px;
	public final AmiColumn exTable_basePx;
	public final AmiColumn exTable_baseCurrency;
	public final AmiColumn exTable_sector;
	public final AmiColumn exTable_side;
	public final AmiColumn exTable_size;
	public final AmiColumn exTable_status;
	public final AmiColumn exTable_sym;
	public final AmiColumn exTable_system;
	public final AmiColumn exTable_t1;
	public final AmiColumn exTable_time;
	public final AmiColumn exTable_inSpread;
	public final AmiColumn exTable_inReg;
	public final AmiColumn exTable_bid;
	public final AmiColumn exTable_ask;
	public final AmiColumn exTable_maxAsk;
	public final AmiColumn exTable_minBid;
	public final AmiColumn exTable_evBid;
	public final AmiColumn exTable_evAsk;
	public final AmiColumn exTable_value;
	public final AmiColumn exTable_evMinBid;
	public final AmiColumn exTable_evMaxAsk;
	public final AmiColumn exTable_t5;
	public final AmiColumn exTable_strategy;

	public final AmiTable nbboTable;
	public final AmiColumn nbboTable_ask;
	public final AmiColumn nbboTable_askSize;
	public final AmiColumn nbboTable_bid;
	public final AmiColumn nbboTable_bidSize;
	public final AmiColumn nbboTable_bidEx;
	public final AmiColumn nbboTable_askEx;
	public final AmiColumn nbboTable_sym;
	public final AmiColumn nbboTable_time;

	public final AmiTable oTable;
	public final AmiColumn oTable_account;
	public final AmiColumn oTable_ask;
	public final AmiColumn oTable_bid;
	public final AmiColumn oTable_dailyValue;
	public final AmiColumn oTable_dailyVolume;
	public final AmiColumn oTable_darkCnt;
	public final AmiColumn oTable_darkVal;
	public final AmiColumn oTable_darkVol;
	public final AmiColumn oTable_endTime;
	public final AmiColumn oTable_exCnt;
	public final AmiColumn oTable_filled;
	public final AmiColumn oTable_filledValue;
	public final AmiColumn oTable_high;
	public final AmiColumn oTable_industry;
	public final AmiColumn oTable_IS;
	public final AmiColumn oTable_isOpen;
	public final AmiColumn oTable_leaves;
	public final AmiColumn oTable_lho;
	public final AmiColumn oTable_limitPx;
	public final AmiColumn oTable_baseCurrency;
	public final AmiColumn oTable_baseLimitPx;
	public final AmiColumn oTable_liqCnt;
	public final AmiColumn oTable_liqVal;
	public final AmiColumn oTable_liqVol;
	public final AmiColumn oTable_low;
	public final AmiColumn oTable_mktImpact;
	public final AmiColumn oTable_open;
	public final AmiColumn oTable_opportunityCost;
	public final AmiColumn oTable_orderID;
	public final AmiColumn oTable_pendingCnt;
	public final AmiColumn oTable_pendingLatency;
	public final AmiColumn oTable_prevClose;
	public final AmiColumn oTable_processedCnt;
	public final AmiColumn oTable_processedLatency;
	public final AmiColumn oTable_sector;
	public final AmiColumn oTable_side;
	public final AmiColumn oTable_size;
	public final AmiColumn oTable_startMidpointHL;
	public final AmiColumn oTable_startTime;
	public final AmiColumn oTable_startValue;
	public final AmiColumn oTable_startVolume;
	public final AmiColumn oTable_status;
	public final AmiColumn oTable_sym;
	public final AmiColumn oTable_system;
	public final AmiColumn oTable_time;
	public final AmiColumn oTable_t5Vol;
	public final AmiColumn oTable_t5Ev;
	public final AmiColumn oTable_t5Rv;
	public final AmiColumn oTable_bidAgg;
	public final AmiColumn oTable_askAgg;
	public final AmiColumn oTable_processedValue;
	public final AmiColumn oTable_regBidAgg;
	public final AmiColumn oTable_regAskAgg;
	public final AmiColumn oTable_t1Ev;
	public final AmiColumn oTable_t1Vol;
	public final AmiColumn oTable_t1Rv;
	public final AmiColumn oTable_startVol;
	public final AmiColumn oTable_startVal;
	public final AmiColumn oTable_endVol;
	public final AmiColumn oTable_endVal;
	public final AmiColumn oTable_endBid;
	public final AmiColumn oTable_endAsk;
	public final AmiColumn oTable_last;
	public final AmiColumn oTable_intervalVWAP;
	public final AmiColumn oTable_dailyVWAP;
	public final AmiColumn oTable_childCnt;
	public final AmiColumn oTable_routedCnt;
	public final AmiColumn oTable_routedVol;
	public final AmiColumn oTable_routedVal;
	public final AmiColumn oTable_strategy;

	public final AmiTable secMasterTable;
	public final AmiColumn secMasterTable_adv;
	public final AmiColumn secMasterTable_industry;
	public final AmiColumn secMasterTable_mktCap;
	public final AmiColumn secMasterTable_name;
	public final AmiColumn secMasterTable_prevClose;
	public final AmiColumn secMasterTable_sector;
	public final AmiColumn secMasterTable_sym;

	public final AmiTable statsTable;
	public final AmiColumn statsTable_childModifiesCnt;
	public final AmiColumn statsTable_childModifiesMs;
	public final AmiColumn statsTable_childOrdersCnt;
	public final AmiColumn statsTable_childOrdersMs;
	public final AmiColumn statsTable_currentTime;
	public final AmiColumn statsTable_execsCnt;
	public final AmiColumn statsTable_execsMs;
	public final AmiColumn statsTable_historiesCnt;
	public final AmiColumn statsTable_historiesMs;
	public final AmiColumn statsTable_memFree;
	public final AmiColumn statsTable_memMax;
	public final AmiColumn statsTable_memTot;
	public final AmiColumn statsTable_nbbosCnt;
	public final AmiColumn statsTable_nbbosMaxMs;
	public final AmiColumn statsTable_nbbosMinMs;
	public final AmiColumn statsTable_ordersClosedCnt;
	public final AmiColumn statsTable_ordersCnt;
	public final AmiColumn statsTable_ordersMs;
	public final AmiColumn statsTable_ordersOpenedCnt;
	public final AmiColumn statsTable_queueHpSize;
	public final AmiColumn statsTable_queueSize;
	public final AmiColumn statsTable_rawNbbosCnt;
	public final AmiColumn statsTable_rawNbbosMaxMs;
	public final AmiColumn statsTable_rawTradesCnt;
	public final AmiColumn statsTable_rawTradesMaxMs;
	public final AmiColumn statsTable_taqsCnt;
	public final AmiColumn statsTable_taqsMs;
	public final AmiColumn statsTable_timersCnt;
	public final AmiColumn statsTable_timersMs;
	public final AmiColumn statsTable_timersOnOrdersCnt;
	public final AmiColumn statsTable_tradesCnt;
	public final AmiColumn statsTable_tradesMaxMs;
	public final AmiColumn statsTable_tradesMinMs;

	public final AmiTable symTable;
	public final AmiColumn symTable_ask;
	public final AmiColumn symTable_bid;
	public final AmiColumn symTable_high;
	public final AmiColumn symTable_last;
	public final AmiColumn symTable_low;
	public final AmiColumn symTable_open;
	public final AmiColumn symTable_size;
	public final AmiColumn symTable_sym;
	public final AmiColumn symTable_value;
	public final AmiColumn symTable_industry;
	public final AmiColumn symTable_name;
	public final AmiColumn symTable_sector;
	public final AmiColumn symTable_mktCap;
	public final AmiColumn symTable_prevClose;
	public final AmiColumn symTable_updateTime;

	public final AmiTable tradeTable;
	public final AmiColumn tradeTable_ex;
	public final AmiColumn tradeTable_high;
	public final AmiColumn tradeTable_low;
	public final AmiColumn tradeTable_open;
	public final AmiColumn tradeTable_px;
	public final AmiColumn tradeTable_size;
	public final AmiColumn tradeTable_sym;
	public final AmiColumn tradeTable_time;
	public final AmiColumn tradeTable_value;
	public final AmiColumn tradeTable_volume;

	public final AmiTable venueTable;
	public final AmiColumn venueTable_askAgg;
	public final AmiColumn venueTable_bidAgg;
	public final AmiColumn venueTable_exCnt;
	public final AmiColumn venueTable_lit;
	public final AmiColumn venueTable_processedValue;
	public final AmiColumn venueTable_regAskAgg;
	public final AmiColumn venueTable_regBidAgg;
	public final AmiColumn venueTable_regCnt;
	public final AmiColumn venueTable_rvT1;
	public final AmiColumn venueTable_rvT5;
	public final AmiColumn venueTable_side;
	public final AmiColumn venueTable_spreadCnt;
	public final AmiColumn venueTable_t1Cnt;
	public final AmiColumn venueTable_t1Val;
	public final AmiColumn venueTable_t5Cnt;
	public final AmiColumn venueTable_t5Val;
	public final AmiColumn venueTable_venue;
	public final AmiColumn venueTable_volume;
	public final AmiColumn venueTable_routedVal;
	public final AmiColumn venueTable_routedVol;
	public final AmiColumn venueTable_routedCnt;
	public final AmiColumn venueTable_liqVal;
	public final AmiColumn venueTable_liqVol;
	public final AmiColumn venueTable_liqCnt;

	public final AmiTable symSideAggTable;
	public final AmiColumn symSideAggTable_sym;
	public final AmiColumn symSideAggTable_side;
	public final AmiColumn symSideAggTable_industry;
	public final AmiColumn symSideAggTable_sector;

	public final AmiTable adminCommandTable;
	public final AmiColumn statsTable_command;

	public final AmiTable parentAlertsTable;
	public final AmiColumn parentAlerts_type;
	public final AmiColumn parentAlerts_minTime;
	public final AmiColumn parentAlerts_maxTime;
	public final AmiColumn parentAlerts_id;
	public final AmiColumn parentAlerts_cnt;
	public final AmiColumn parentAlerts_severity;
	public final AmiColumn parentAlerts_details;
	public final AmiColumn parentAlerts_assignedTo;

	public final AmiTable childAlertsTable;
	public final AmiColumn childAlertsTable_modifiedBy;
	public final AmiColumn childAlertsTable_assignedTo;
	public final AmiColumn childAlertsTable_params;
	public final AmiColumn childAlertsTable_id;
	//public final AmiColumn childAlertsTable_description;
	public final AmiColumn childAlertsTable_type;
	public final AmiColumn childAlertsTable_comment;
	public final AmiColumn childAlertsTable_time;
	public final AmiColumn childAlertsTable_severity;
	public final AmiColumn childAlertsTable_action;
	public final AmiColumn childAlertsTable_parentId;
	public final AmiColumn childAlertsTable_sym;
	public final AmiColumn childAlertsTable_orderId;
	public final AmiColumn childAlertsTable_account;
	public final AmiColumn childAlertsTable_system;
	public final AmiColumn childAlertsTable_sector;
	public final AmiColumn childAlertsTable_industry;
	public final AmiColumn childAlertsTable_strategy;
	public final AmiColumn childAlertsTable_exchange;
	public final AmiColumn childAlertsTable_details;
	public final AmiColumn childAlertsTable_modifiedSid;
	public final AmiColumn childAlertsTable_modifiedIp;

	public final AmiTable fxRateTable;
	public final AmiColumn fxRateTable_baseCurrency;
	public final AmiColumn fxRateTable_counterCurrency;
	public final AmiColumn fxRateTable_rate;

	public final AmiTable ordersByAccountSideTable;
	public final AmiColumn ordersByAccountSideTable_account;
	public final AmiColumn ordersByAccountSideTable_filledValue;
	public final AmiColumn ordersByAccountSideTable_openValue;

	public final AmiTable ordersBySymSideTable;
	public final AmiColumn ordersBySymSideTable_sym;
	public final AmiColumn ordersBySymSideTable_cnt;
	public final AmiColumn ordersBySymSideTable_exCnt;
	public final AmiColumn ordersBySymSideTable_side;
	public final AmiColumn ordersBySymSideTable_messageRate;
	public final AmiColumn ordersBySymSideTable_exMessageRate;

	public AnvilSchema(AmiImdb imdb) {
		//Stats
		this.statsTable = imdb.getAmiTable("Stats");
		this.statsTable_currentTime = statsTable.getColumn("currentTime");
		this.statsTable_ordersCnt = statsTable.getColumn("ordersCnt");
		this.statsTable_ordersOpenedCnt = statsTable.getColumn("ordersOpenedCnt");
		this.statsTable_ordersClosedCnt = statsTable.getColumn("ordersClosedCnt");
		this.statsTable_ordersMs = statsTable.getColumn("ordersMs");
		this.statsTable_execsCnt = statsTable.getColumn("execsCnt");
		this.statsTable_execsMs = statsTable.getColumn("execsMs");
		this.statsTable_timersCnt = statsTable.getColumn("timersCnt");
		this.statsTable_timersOnOrdersCnt = statsTable.getColumn("timersOnOrdersCnt");
		this.statsTable_timersMs = statsTable.getColumn("timersMs");
		this.statsTable_taqsCnt = statsTable.getColumn("taqsCnt");
		this.statsTable_taqsMs = statsTable.getColumn("taqsMs");
		this.statsTable_historiesCnt = statsTable.getColumn("historiesCnt");
		this.statsTable_historiesMs = statsTable.getColumn("historiesMs");
		this.statsTable_rawNbbosCnt = statsTable.getColumn("rawNbbosCnt");
		this.statsTable_rawNbbosMaxMs = statsTable.getColumn("rawNbbosMaxMs");
		this.statsTable_rawTradesCnt = statsTable.getColumn("rawTradesCnt");
		this.statsTable_rawTradesMaxMs = statsTable.getColumn("rawTradesMaxMs");
		this.statsTable_nbbosCnt = statsTable.getColumn("nbbosCnt");
		this.statsTable_nbbosMaxMs = statsTable.getColumn("nbbosMaxMs");
		this.statsTable_nbbosMinMs = statsTable.getColumn("nbbosMinMs");
		this.statsTable_tradesCnt = statsTable.getColumn("tradesCnt");
		this.statsTable_tradesMaxMs = statsTable.getColumn("tradesMaxMs");
		this.statsTable_tradesMinMs = statsTable.getColumn("tradesMinMs");
		this.statsTable_queueSize = statsTable.getColumn("queueSize");
		this.statsTable_queueHpSize = statsTable.getColumn("queueHpSize");
		this.statsTable_memFree = statsTable.getColumn("memFree");
		this.statsTable_memMax = statsTable.getColumn("memMax");
		this.statsTable_memTot = statsTable.getColumn("memTot");
		this.statsTable_childOrdersCnt = statsTable.getColumn("childOrdersCnt");
		this.statsTable_childModifiesCnt = statsTable.getColumn("childModifiesCnt");
		this.statsTable_childOrdersMs = statsTable.getColumn("childOrdersMs");
		this.statsTable_childModifiesMs = statsTable.getColumn("childModifiesMs");

		//Execution
		this.exTable = imdb.getAmiTable("Execution");
		this.exTable_time = exTable.getColumn("time");
		this.exTable_sym = exTable.getColumn("symbol");
		this.exTable_ex = exTable.getColumn("ex");
		this.exTable_px = exTable.getColumn("px");
		this.exTable_basePx = exTable.getColumn("basePx");
		this.exTable_baseCurrency = exTable.getColumn("baseCurrency");
		this.exTable_size = exTable.getColumn("size");
		this.exTable_status = exTable.getColumn("status");
		this.exTable_oID = exTable.getColumn("oID");
		this.exTable_execId = exTable.getColumn("execId");
		this.exTable_parentId = exTable.getColumn("parentId");
		this.exTable_side = exTable.getColumn("side");
		this.exTable_t1 = exTable.getColumn("t1");
		this.exTable_account = exTable.getColumn("account");
		this.exTable_system = exTable.getColumn("system");
		this.exTable_industry = exTable.getColumn("industry");
		this.exTable_sector = exTable.getColumn("sector");
		this.exTable_prevClose = exTable.getColumn("prevClose");
		this.exTable_execIndicator = exTable.getColumn("execIndicator");
		this.exTable_t5 = exTable.getColumn("t5");
		this.exTable_bid = exTable.getColumn("bid");
		this.exTable_ask = exTable.getColumn("ask");
		this.exTable_maxAsk = exTable.getColumn("maxAsk");
		this.exTable_minBid = exTable.getColumn("minBid");
		this.exTable_evBid = exTable.getColumn("evBid");
		this.exTable_evAsk = exTable.getColumn("evAsk");
		this.exTable_evMinBid = exTable.getColumn("evMinBid");
		this.exTable_evMaxAsk = exTable.getColumn("evMaxAsk");
		this.exTable_value = exTable.getColumn("value");
		this.exTable_inSpread = exTable.getColumn("inSpread");
		this.exTable_inReg = exTable.getColumn("inReg");
		this.exTable_strategy = exTable.getColumn("strategy");

		//Orders
		this.oTable = imdb.getAmiTable("ParentOrder");
		this.oTable_orderID = oTable.getColumn("orderID");
		this.oTable_sym = oTable.getColumn("symbol");
		this.oTable_side = oTable.getColumn("side");
		this.oTable_limitPx = oTable.getColumn("limitPx");
		this.oTable_baseCurrency = oTable.getColumn("baseCurrency");
		this.oTable_baseLimitPx = oTable.getColumn("baseLimitPx");
		this.oTable_size = oTable.getColumn("size");
		this.oTable_dailyVolume = oTable.getColumn("dailyVolume");
		this.oTable_dailyValue = oTable.getColumn("dailyValue");
		this.oTable_open = oTable.getColumn("open");
		this.oTable_low = oTable.getColumn("low");
		this.oTable_high = oTable.getColumn("high");
		this.oTable_time = oTable.getColumn("time");
		this.oTable_filled = oTable.getColumn("filled");
		this.oTable_filledValue = oTable.getColumn("filledValue");
		this.oTable_account = oTable.getColumn("account");
		this.oTable_system = oTable.getColumn("system");
		this.oTable_startTime = oTable.getColumn("startTime");
		this.oTable_startMidpointHL = oTable.getColumn("startMidpointHL");
		this.oTable_startValue = oTable.getColumn("startVal");
		this.oTable_startVolume = oTable.getColumn("startVol");
		this.oTable_endTime = oTable.getColumn("endTime");
		this.oTable_sector = oTable.getColumn("sector");
		this.oTable_industry = oTable.getColumn("industry");
		this.oTable_isOpen = oTable.getColumn("isOpen");
		this.oTable_prevClose = oTable.getColumn("prevClose");
		this.oTable_exCnt = oTable.getColumn("exCnt");
		this.oTable_lho = oTable.getColumn("lho");
		this.oTable_IS = oTable.getColumn("IS");
		this.oTable_bid = oTable.getColumn("bid");
		this.oTable_ask = oTable.getColumn("ask");
		this.oTable_mktImpact = oTable.getColumn("mktImpact");
		this.oTable_opportunityCost = oTable.getColumn("opportunityCost");
		this.oTable_status = oTable.getColumn("status");
		this.oTable_leaves = oTable.getColumn("leaves");
		this.oTable_pendingCnt = oTable.getColumn("pendingCnt");
		this.oTable_pendingLatency = oTable.getColumn("pendingLatency");
		this.oTable_processedCnt = oTable.getColumn("processedCnt");
		this.oTable_processedLatency = oTable.getColumn("processedLatency");
		this.oTable_darkVal = oTable.getColumn("darkVal");
		this.oTable_darkVol = oTable.getColumn("darkVol");
		this.oTable_darkCnt = oTable.getColumn("darkCnt");
		this.oTable_liqVal = oTable.getColumn("liqVal");
		this.oTable_liqVol = oTable.getColumn("liqVol");
		this.oTable_liqCnt = oTable.getColumn("liqCnt");
		this.oTable_startVol = oTable.getColumn("startVol");
		this.oTable_startVal = oTable.getColumn("startVal");
		this.oTable_endVol = oTable.getColumn("endVol");
		this.oTable_endVal = oTable.getColumn("endVal");
		this.oTable_endBid = oTable.getColumn("endBid");
		this.oTable_endAsk = oTable.getColumn("endAsk");
		this.oTable_last = oTable.getColumn("last");
		this.oTable_intervalVWAP = oTable.getColumn("intervalVWAP");
		this.oTable_dailyVWAP = oTable.getColumn("dailyVWAP");
		this.oTable_bidAgg = oTable.getColumn("bidAgg");
		this.oTable_askAgg = oTable.getColumn("askAgg");
		this.oTable_regBidAgg = oTable.getColumn("regBidAgg");
		this.oTable_regAskAgg = oTable.getColumn("regAskAgg");
		this.oTable_processedValue = oTable.getColumn("processedValue");
		this.oTable_t1Vol = oTable.getColumn("t1Vol");
		this.oTable_t1Ev = oTable.getColumn("evT1");
		this.oTable_t1Rv = oTable.getColumn("rvT1");
		this.oTable_t5Vol = oTable.getColumn("t5Vol");
		this.oTable_t5Ev = oTable.getColumn("evT5");
		this.oTable_t5Rv = oTable.getColumn("rvT5");
		this.oTable_childCnt = oTable.getColumn("childCnt");
		this.oTable_routedCnt = oTable.getColumn("routedCnt");
		this.oTable_routedVol = oTable.getColumn("routedVol");
		this.oTable_routedVal = oTable.getColumn("routedVal");
		this.oTable_strategy = oTable.getColumn("strategy");

		//Symbol
		this.symTable = imdb.getAmiTable("Symbol");
		this.symTable_sym = symTable.getColumn("symbol");
		this.symTable_bid = symTable.getColumn("bid");
		this.symTable_ask = symTable.getColumn("ask");
		this.symTable_size = symTable.getColumn("size");
		this.symTable_value = symTable.getColumn("value");
		this.symTable_high = symTable.getColumn("high");
		this.symTable_low = symTable.getColumn("low");
		this.symTable_last = symTable.getColumn("last");
		this.symTable_open = symTable.getColumn("open");
		this.symTable_industry = symTable.getColumn("industry");
		this.symTable_name = symTable.getColumn("name");
		this.symTable_sector = symTable.getColumn("sector");
		this.symTable_mktCap = symTable.getColumn("mktCap");
		this.symTable_prevClose = symTable.getColumn("prevClose");
		this.symTable_updateTime = symTable.getColumn("updateTime");

		//NBBO
		this.nbboTable = imdb.getAmiTable("NBBO");
		this.nbboTable_time = nbboTable.getColumn("time");
		this.nbboTable_sym = nbboTable.getColumn("symbol");
		this.nbboTable_bidEx = nbboTable.getColumn("bidEx");
		this.nbboTable_askEx = nbboTable.getColumn("askEx");
		this.nbboTable_bid = nbboTable.getColumn("bid");
		this.nbboTable_bidSize = nbboTable.getColumn("bidSize");
		this.nbboTable_ask = nbboTable.getColumn("ask");
		this.nbboTable_askSize = nbboTable.getColumn("askSize");

		//SecMaster
		this.secMasterTable = imdb.getAmiTable("SecMaster");
		this.secMasterTable_sym = secMasterTable.getColumn("symbol");
		this.secMasterTable_name = secMasterTable.getColumn("name");
		this.secMasterTable_sector = secMasterTable.getColumn("sector");
		this.secMasterTable_industry = secMasterTable.getColumn("industry");
		this.secMasterTable_mktCap = secMasterTable.getColumn("mktCap");
		this.secMasterTable_prevClose = secMasterTable.getColumn("prevClose");
		this.secMasterTable_adv = secMasterTable.getColumn("adv");

		//ChildOrders
		this.childOrdersTable = imdb.getAmiTable("childOrders");
		this.childOrdersTable_parentId = childOrdersTable.getColumn("parentId");
		this.childOrdersTable_qty = childOrdersTable.getColumn("size");
		this.childOrdersTable_limitPx = childOrdersTable.getColumn("limitPx");
		this.childOrdersTable_baseCurrency = childOrdersTable.getColumn("baseCurrency");
		this.childOrdersTable_baseLimitPx = childOrdersTable.getColumn("baseLimitPx");
		this.childOrdersTable_chainId = childOrdersTable.getColumn("chainId");
		this.childOrdersTable_clOrderId = childOrdersTable.getColumn("clOrderId");
		this.childOrdersTable_status = childOrdersTable.getColumn("status");
		this.childOrdersTable_replaced = childOrdersTable.getColumn("replaced");
		this.childOrdersTable_pendingCnt = childOrdersTable.getColumn("pendingCnt");
		this.childOrdersTable_pendingLatency = childOrdersTable.getColumn("pendingLatency");
		this.childOrdersTable_processedCnt = childOrdersTable.getColumn("processedCnt");
		this.childOrdersTable_processedLatency = childOrdersTable.getColumn("processedLatency");
		this.childOrdersTable_filledValue = childOrdersTable.getColumn("filledValue");
		this.childOrdersTable_filledQty = childOrdersTable.getColumn("filledQty");
		this.childOrdersTable_availQty = childOrdersTable.getColumn("availQty");
		this.childOrdersTable_availVal = childOrdersTable.getColumn("availVal");
		this.childOrdersTable_openQty = childOrdersTable.getColumn("openQty");
		this.childOrdersTable_time = childOrdersTable.getColumn("time");
		this.childOrdersTable_updateTime = childOrdersTable.getColumn("updateTime");
		this.childOrdersTable_openVal = childOrdersTable.getColumn("openVal");
		this.childOrdersTable_symbol = childOrdersTable.getColumn("symbol");

		//ChildMessages
		this.childOrderTable = imdb.getAmiTable("ChildOrder");
		this.childOrderTable_time = childOrderTable.getColumn("time");
		this.childOrderTable_parentId = childOrderTable.getColumn("parentId");
		this.childOrderTable_qty = childOrderTable.getColumn("size");
		this.childOrderTable_limitPx = childOrderTable.getColumn("limitPx");
		this.childOrderTable_baseCurrency = childOrderTable.getColumn("baseCurrency");
		this.childOrderTable_baseLimitPx = childOrderTable.getColumn("baseLimitPx");
		this.childOrderTable_clOrderId = childOrderTable.getColumn("clOrdId");
		this.childOrderTable_origClOrderId = childOrderTable.getColumn("origClOrdId");
		this.childOrderTable_status = childOrderTable.getColumn("status");
		this.childOrderTable_symbol = childOrderTable.getColumn("symbol");
		this.childOrderTable_chainId = childOrderTable.getColumn("chainId");

		//Venues
		this.venueTable = imdb.getAmiTable("Venues");
		this.venueTable_exCnt = venueTable.getColumn("exCnt");
		this.venueTable_spreadCnt = venueTable.getColumn("spreadCnt");
		this.venueTable_regCnt = venueTable.getColumn("regCnt");
		this.venueTable_volume = venueTable.getColumn("volume");
		this.venueTable_venue = venueTable.getColumn("venue");
		this.venueTable_side = venueTable.getColumn("side");
		this.venueTable_bidAgg = venueTable.getColumn("bidAgg");
		this.venueTable_askAgg = venueTable.getColumn("askAgg");
		this.venueTable_regBidAgg = venueTable.getColumn("regBidAgg");
		this.venueTable_regAskAgg = venueTable.getColumn("regAskAgg");
		this.venueTable_processedValue = venueTable.getColumn("processedValue");
		this.venueTable_lit = venueTable.getColumn("lit");
		this.venueTable_rvT1 = venueTable.getColumn("rvT1");
		this.venueTable_t1Val = venueTable.getColumn("t1Val");
		this.venueTable_t1Cnt = venueTable.getColumn("t1Cnt");
		this.venueTable_rvT5 = venueTable.getColumn("rvT5");
		this.venueTable_t5Val = venueTable.getColumn("t5Val");
		this.venueTable_t5Cnt = venueTable.getColumn("t5Cnt");
		this.venueTable_liqCnt = venueTable.getColumn("liqCnt");
		this.venueTable_liqVol = venueTable.getColumn("liqVol");
		this.venueTable_liqVal = venueTable.getColumn("liqVal");
		this.venueTable_routedCnt = venueTable.getColumn("routedCnt");
		this.venueTable_routedVol = venueTable.getColumn("routedVol");
		this.venueTable_routedVal = venueTable.getColumn("routedVal");

		//Trade
		this.tradeTable = imdb.getAmiTable("Trade");
		this.tradeTable_time = tradeTable.getColumn("time");
		this.tradeTable_sym = tradeTable.getColumn("symbol");
		this.tradeTable_ex = tradeTable.getColumn("ex");
		this.tradeTable_px = tradeTable.getColumn("px");
		this.tradeTable_size = tradeTable.getColumn("size");
		this.tradeTable_volume = tradeTable.getColumn("volume");
		this.tradeTable_value = tradeTable.getColumn("value");
		this.tradeTable_high = tradeTable.getColumn("high");
		this.tradeTable_low = tradeTable.getColumn("low");
		this.tradeTable_open = tradeTable.getColumn("open");

		//ChildModifies
		this.childModifyTable = imdb.getAmiTable("ChildAck");
		this.childModifyTable_time = childModifyTable.getColumn("time");
		this.childModifyTable_symbol = childModifyTable.getColumn("symbol");
		this.childModifyTable_clOrderId = childModifyTable.getColumn("clOrdId");
		this.childModifyTable_status = childModifyTable.getColumn("status");
		this.childModifyTable_chainId = childModifyTable.getColumn("chainId");

		this.symSideAggTable = imdb.getAmiTable("OrdersBySymSide");
		this.symSideAggTable_sym = symSideAggTable.getColumn("symbol");
		this.symSideAggTable_side = symSideAggTable.getColumn("side");
		this.symSideAggTable_sector = symSideAggTable.getColumn("sector");
		this.symSideAggTable_industry = symSideAggTable.getColumn("industry");

		this.adminCommandTable = imdb.getAmiTable("AdminCommand");
		this.statsTable_command = adminCommandTable.getColumn("command");

		//ParentAlerts
		this.parentAlertsTable = imdb.getAmiTable("ParentAlerts");
		this.parentAlerts_type = parentAlertsTable.getColumn("type");
		this.parentAlerts_minTime = parentAlertsTable.getColumn("minTime");
		this.parentAlerts_maxTime = parentAlertsTable.getColumn("maxTime");
		this.parentAlerts_id = parentAlertsTable.getColumn("id");
		this.parentAlerts_cnt = parentAlertsTable.getColumn("cnt");
		this.parentAlerts_severity = parentAlertsTable.getColumn("severity");
		this.parentAlerts_details = parentAlertsTable.getColumn("details");
		this.parentAlerts_assignedTo = parentAlertsTable.getColumn("assignedTo");

		//ChildAlerts
		this.childAlertsTable = imdb.getAmiTable("ChildAlert");
		this.childAlertsTable_modifiedBy = childAlertsTable.getColumn("modifiedBy");
		this.childAlertsTable_modifiedSid = childAlertsTable.getColumn("modifiedSid");
		this.childAlertsTable_modifiedIp = childAlertsTable.getColumn("modifiedIp");
		this.childAlertsTable_assignedTo = childAlertsTable.getColumn("assignedTo");
		this.childAlertsTable_params = childAlertsTable.getColumn("params");
		this.childAlertsTable_id = childAlertsTable.getColumn("id");
		//this.childAlertsTable_description = childAlertsTable.getColumn("description");
		this.childAlertsTable_type = childAlertsTable.getColumn("type");
		this.childAlertsTable_comment = childAlertsTable.getColumn("comment");
		this.childAlertsTable_time = childAlertsTable.getColumn("time");
		this.childAlertsTable_severity = childAlertsTable.getColumn("severity");
		this.childAlertsTable_action = childAlertsTable.getColumn("action");
		this.childAlertsTable_parentId = childAlertsTable.getColumn("parentId");
		this.childAlertsTable_sym = childAlertsTable.getColumn("symbol");
		this.childAlertsTable_orderId = childAlertsTable.getColumn("orderId");
		this.childAlertsTable_account = childAlertsTable.getColumn("account");
		this.childAlertsTable_system = childAlertsTable.getColumn("system");
		this.childAlertsTable_sector = childAlertsTable.getColumn("sector");
		this.childAlertsTable_industry = childAlertsTable.getColumn("industry");
		this.childAlertsTable_strategy = childAlertsTable.getColumn("strategy");
		this.childAlertsTable_exchange = childAlertsTable.getColumn("ex");
		this.childAlertsTable_details = childAlertsTable.getColumn("details");

		//FxSpot
		this.fxRateTable = imdb.getAmiTable("FxRate");
		this.fxRateTable_baseCurrency = fxRateTable.getColumn("baseCurrency");
		this.fxRateTable_counterCurrency = fxRateTable.getColumn("counterCurrency");
		this.fxRateTable_rate = fxRateTable.getColumn("rate");

		//OrdersByAccountSide
		this.ordersByAccountSideTable = imdb.getAmiTable("OrdersByAccountSide");
		this.ordersByAccountSideTable_account = ordersByAccountSideTable.getColumn("account");
		this.ordersByAccountSideTable_filledValue = ordersByAccountSideTable.getColumn("filledValue");
		this.ordersByAccountSideTable_openValue = ordersByAccountSideTable.getColumn("openValue");

		//OrdersBySymSide
		this.ordersBySymSideTable = imdb.getAmiTable("OrdersBySymSide");
		this.ordersBySymSideTable_side = ordersBySymSideTable.getColumn("side");
		this.ordersBySymSideTable_sym = ordersBySymSideTable.getColumn("symbol");
		this.ordersBySymSideTable_cnt = ordersBySymSideTable.getColumn("cnt");
		this.ordersBySymSideTable_exCnt = ordersBySymSideTable.getColumn("exCnt");
		this.ordersBySymSideTable_messageRate = ordersBySymSideTable.getColumn("messageRate");
		this.ordersBySymSideTable_exMessageRate = ordersBySymSideTable.getColumn("exMessageRate");
	}

}
